// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqup1u--WDxugU6iiKSusnPjAwNYDEhGo',
    appId: '1:556816178700:web:60c263cd4f91302df9d829',
    messagingSenderId: '556816178700',
    projectId: 'n8nflutter',
    authDomain: 'n8nflutter.firebaseapp.com',
    storageBucket: 'n8nflutter.firebasestorage.app',
    measurementId: 'G-FQL0N7JL2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDudHi9SyzNA1kpGiln5spsLfbPtqzBNts',
    appId: '1:556816178700:android:59210bb495bade9ff9d829',
    messagingSenderId: '556816178700',
    projectId: 'n8nflutter',
    storageBucket: 'n8nflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAAcccR6U7r4GTSjy23ZL9i74py5xCP3A',
    appId: '1:556816178700:ios:95ccb62fd98f4aaff9d829',
    messagingSenderId: '556816178700',
    projectId: 'n8nflutter',
    storageBucket: 'n8nflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterCreate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAAcccR6U7r4GTSjy23ZL9i74py5xCP3A',
    appId: '1:556816178700:ios:95ccb62fd98f4aaff9d829',
    messagingSenderId: '556816178700',
    projectId: 'n8nflutter',
    storageBucket: 'n8nflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterCreate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqup1u--WDxugU6iiKSusnPjAwNYDEhGo',
    appId: '1:556816178700:web:b298a33f0cf30cadf9d829',
    messagingSenderId: '556816178700',
    projectId: 'n8nflutter',
    authDomain: 'n8nflutter.firebaseapp.com',
    storageBucket: 'n8nflutter.firebasestorage.app',
    measurementId: 'G-PD2V9LJJRC',
  );
}
